Output to HIE_BIOS_OUTPUT when set.

diff --git a/script/ghci-flags b/script/ghci-flags
--- a/script/ghci-flags
+++ b/script/ghci-flags
@@ -8,6 +8,9 @@ cd $(dirname "$0")/..
 root="$(pwd)"
 ghc_version="$(ghc --numeric-version)"
 
+# recent hie-bios requires us to output to the file at $HIE_BIOS_OUTPUT, but older builds & script/repl don’t set that var, so we default it to stdout
+output_file="${HIE_BIOS_OUTPUT:-/dev/stdout}"
+
 if [ "$1" == "--builddir" ]; then
   repl_builddir="$2"
   shift 2
@@ -15,39 +18,43 @@ else
   repl_builddir=dist-newstyle
 fi
 
-echo "-O0"
-echo "-ignore-dot-ghci"
+function flags {
+  echo "-O0"
+  echo "-ignore-dot-ghci"
 
-echo "-outputdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
-echo "-odir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
-echo "-hidir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
-echo "-stubdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
+  echo "-outputdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
+  echo "-odir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
+  echo "-hidir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
+  echo "-stubdir $repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl"
 
-echo "-i$root/app"
-echo "-i$root/src"
+  echo "-i$root/app"
+  echo "-i$root/src"
 
-echo "-optP-include"
-echo "-optP$root/$repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl/autogen/cabal_macros.h"
+  echo "-optP-include"
+  echo "-optP$root/$repl_builddir/build/x86_64-osx/ghc-$ghc_version/build-repl/autogen/cabal_macros.h"
 
-echo "-hide-all-packages"
+  echo "-hide-all-packages"
 
-# Emit package flags from the environment file, removing comments & prefixing with -
-cabal exec --builddir="$repl_builddir" -v0 bash -- -c 'cat "$GHC_ENVIRONMENT"' | grep -v '^--' | sed -e 's/^/-/'
+  # Emit package flags from the environment file, removing comments & prefixing with -
+  cabal exec --builddir="$repl_builddir" -v0 bash -- -c 'cat "$GHC_ENVIRONMENT"' | grep -v '^--' | sed -e 's/^/-/'
 
-echo "-XHaskell2010"
+  echo "-XHaskell2010"
 
-echo "-Wwarn"
+  echo "-Wwarn"
 
-echo "-Weverything"
-echo "-Wno-all-missed-specialisations"
-echo "-Wno-implicit-prelude"
-echo "-Wno-missed-specialisations"
-echo "-Wno-missing-import-lists"
-echo "-Wno-missing-local-signatures"
-echo "-Wno-monomorphism-restriction"
-echo "-Wno-name-shadowing"
-echo "-Wno-safe"
-echo "-Wno-unsafe"
+  echo "-Weverything"
+  echo "-Wno-all-missed-specialisations"
+  echo "-Wno-implicit-prelude"
+  echo "-Wno-missed-specialisations"
+  echo "-Wno-missing-import-lists"
+  echo "-Wno-missing-local-signatures"
+  echo "-Wno-monomorphism-restriction"
+  echo "-Wno-name-shadowing"
+  echo "-Wno-safe"
+  echo "-Wno-unsafe"
 
-[[ "$ghc_version" = 8.6.* ]] && echo "-Wno-star-is-type" || true
-[[ "$ghc_version" = 8.8.* ]] && echo "-Wno-missing-deriving-strategies" || true
+  [[ "$ghc_version" = 8.6.* ]] && echo "-Wno-star-is-type" || true
+  [[ "$ghc_version" = 8.8.* ]] && echo "-Wno-missing-deriving-strategies" || true
+}
+
+flags > "$output_file"
